shared:
    image: kirillo/docker-android-build-tools
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - assemble: ./gradlew :app:assembleDebug
            - test: ./gradlew :app:assembleDebugAndroidTest