shared:
    image: circleci/android
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - assemble: ./gradlew :app:assembleDebug
            - test: ./gradlew :app:assembleDebugAndroidTest